# Site Settings
title: dev*
email: function.bind@gmail.com
description: some sugars for dev
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://bl.oror.io" # the base hostname & protocol for your site
google_analytics: "UA-XXXXXXXX-X"

# User Settings
username: dev*
user_description: Frontend Developer
disqus_username: dalgos

# Social Media
# Remove the item if you don't need it
github_username: dalgos
facebook_username: dalgos
twitter_username: dalgos
instagram_username: dalgos
linkedin_username: dalgos
medium_username: dalgos

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# Plugins
plugins:
  - jemoji

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: About
    url: /about/
  - title: Contact
    url: /contact/

# Exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
